### ISSUE TITLE
Expand section on Publishing

### ISSUE THREAD

**Issue by csarven** [w3c/websub#100]
The *Publishing* section: https://www.w3.org/TR/websub/#publishing is under specified. I think https://www.w3.org/TR/ldn/ is a good candidate as a possible mechanism.

**Comment by rhiaro** [comment]
I agree it's underspecified. I think at least some informative examples of possible ways to notify the hub of new content would be helpful.

**Comment by sandhawke** [comment]
Authentication seems to me to be 90% of the problem here.

One clever solution is to use webmention.    If you run your webmention-notify routine on any modified content, as you might do anyway, it should find the rel=hub link, and do discovery on the hub, and notify it if it can.     In other words, make your hubs be webmention receivers.

I'm not positive whether typical webmention code would find the hub link in the <head> but it seems to be within the allowed behavior.

**Comment by julien51** [comment]
It is under-specified on purpose, because there are many ways of doing this and all of them are right as long as:
> the hub is eventually able send the updated payload to the subscribers.

I would be sad to impose one approach that would not cover all possible cases while making hub implementions non-compliant.
I guess its often the case with protocols that specify how 3 entities interact (publishers, hub and subscriber). From the subscriber POV, how the pub and hub interact is out of scope, similarly, from the publisher POV, how to the hub and sub interact is irrelevant.

Maybe the publisher <-> hub relationship belongs in another spec?

**Comment by dissolve** [comment]
:+1: on leaving it to another spec.
Perhaps we should add a note to say that it is intentionally left out of the scope and suggest possible mechanisms such as webmention.

**Comment by aaronpk** [comment]
I'm all for having this in another spec. The main reason to not include it in the core spec is that some publishers have built-in hubs, so they have their own backchannel to communicate. Imagine the Wordpress WebSub plugin, where the plugin knows when a new post is published because it's part of the same software. It makes no sense for the plugin to be considered non-conformant because it doesn't also speak the publisher protocol.

A while ago, I wrote up [a how-to guide](https://indieweb.org/How_to_publish_and_consume_WebSub#How_to_Publish) that specifies this relationship based on what Superfeedr and Switchboard implemented for their publishing protocol. It's basically a logical extension of the subscription protocol.

```
hub.mode=publish&
hub.topic=http://example.com/feed
```

**Comment by dissolve** [comment]
How about 
"Note:
The spec considers the mechanism for notifying the hub to be out of scope of this specification.  Leaving this unspecified allows for the hub to be integrated directly in to the publisher or to use other specs such as <webmention> or <ldn>"
?

**Comment by csarven** [comment]
I lost interest in this issue as soon as a clever analysis with stats made its appearance. Please carry on with this issue as you all see fit.

**Comment by sandhawke** [comment]
I'm not seeing any stats....

That said, if you've lost interest, and I see everyone else has expressed satisfaction with the status quo, I'm closing this, commenter (some version of) satisfied.   Re-open or explain if you like.
