### ISSUE TITLE
Temporary vs Permanent Redirect

### ISSUE THREAD

**Issue by billc** [w3c/websub#150]
Is there some implied action a subscriber should take when receiving a 307 Temporary Redirect versus a 308 Permanent Redirect when subscribing to a topic URL? Reading 6.1.2 Subscription Response Details, I feel as though I am missing some important step to account for in a subscriber.

**Comment by aaronpk** [comment]
There isn't anything unique about WebSub to the handling of the response code beyond what HTTP says. Ultimately the difference doesn't matter that much, since in the end the subscriber will end up doing discovery at the topic URL to find the hub again when the subscription expires, and it will either find the old hub URL (and still encounter this redirect) or find the new hub URL.
