### ISSUE TITLE
Unilateral unsubscription notifications

### ISSUE THREAD

**Issue by tonyg** [w3c/websub#16]
The hub as specified in the draft of 20 Oct 2016 can delete a subscription unilaterally from time to time:
- when a lease expires
- (perhaps) when a content distribution attempt fails "often enough" (see issue #15)
- (perhaps) in other situations?

It may be worth considering sending a notification of unsubscription when any of these events occur.

Such a notification could be similar to an unsubscription _verification_, except that the response from the subscriber would be ignored (and `hub.challenge` would be omitted, etc).

**Comment by tonyg** [comment]
Ah! Perhaps that's the intent of the "subscription denied" (section 4.2)? If so, perhaps it'd be good to separate it out into a separate subsection of its own -- "Subscription Cancellation Notification" or similar -- and to refer to that section in the handful of places necessary.

I think also that the following language:

> The Subscriber SHOULD then consider that the subscription is not possible anymore.

is unclear; does it mean just that the subscription state has been deleted, or does it mean that if an attempt to reestablish the subscription is made, that attempt will fail?

Perhaps include in the notification something like: **hub.retry**, a number (see issue #18) of seconds that a subscriber SHOULD wait before attempting subscription reestablishment; may be the string `never`, indicating that the subscription MUST NOT be reattempted

**Comment by dret** [comment]
with #20 we could go all meta and allow (if so wished by the server as a value-added service) a client to *subscribe to updates to subscription resource(s)*. in this case, if a subscription expires, the client will be notified of this event.

**Comment by aaronpk** [comment]
I think the intent of "denied" is stronger than just an expired subscription. I believe it was intended to be used more like an `HTTP 403 Forbidden` response.

With relatively short lease durations, there isn't a lot of benefit of notifying the subscriber that the subscription expired. The subscriber is expected to renew the subscription before the existing lease ends anyway.

**Comment by tonyg** [comment]
In cases where a subscription is terminated due to failing deliveries, having a notification sent to the same URL that's failing for deliveries seems problematic in any case. Hmm. Without wanting to comment on other aspects of @dret's "meta" idea yet, it does have one clear benefit: a "management" callback URL distinct from the "data" callback URL could be supplied for meta-events.

**Comment by julien51** [comment]
I don't think there is a need to send "unubscription" verifications.

* when a lease expires

> The subscriber knows about the lease period. That would be redundant.

* (perhaps) when a content distribution attempt fails "often enough" (see issue #15)

> The hub is not supposed to drop subscriptions... just notifications!

* (perhaps) in other situations?

> Please give an example ;)

For now, I'm closing this. Feel free to re-open if you have other examples.

**Comment by tonyg** [comment]
(NB: I'm talking about unsubscription *notifications*, not *verifications*)

> The subscriber knows about the lease period. That would be redundant.

Yes, but not sending a notification requires the subscriber to maintain state. If a notification were available, the subscriber could be implemented statelessly. The hub MUST remember state about the subscription and about the lease duration; with a notification, the subscriber MAY remember state, but without a notification, the subscriber MUST remember state.

> The hub is not supposed to drop subscriptions... just notifications!

What happens when a subscription callback endpoint goes away forever? I think the limit, the hub must be allowed to drop subscriptions.

> Please give an example ;)

:-) Hmm. What about a permission change? A) Subscription established, including a "subscription validation" step. B) The topic's permissions change in such a way that a similar, new subscription would fail for permission-denied reasons, and the established subscription is terminated as a result. C) Notification!

**Comment by julien51** [comment]
Any "sane" subscriber has to keep state for each subscription (the unique callback URL, the secret... etc) so I think it's not unreasonable to ask to keep track of the lease as well. From experience this is what a lot of subscribers do.

> What happens when a subscription callback endpoint goes away forever? I think in the limit, the hub must be allowed to drop subscriptions.
Expirations. The main reason to have leases is exactly for that. 

I guess in this case as well expirations can fix this, but not in the timeliest manner. Also I have not seen this in the wild at this point and I believe the policy is to come up with a protocol which matches practices. 

Also I think if this becomes an issue in the future, it becomes fairly simple to add such a mechanism where the hub informs the subscriber (hub.mode=denied).

**Comment by tonyg** [comment]
> Any "sane" subscriber has to keep state for each subscription (the unique callback URL, the secret... etc)

I don't agree; it seems perfectly possible to encode everything about the context that a subscriber might need into the callback URL, which is supplied by the hub to the subscriber at each interaction, meaning that the subscriber can operate fully statelessly (modulo this issue).

**Comment by dissolve** [comment]
Wouldn't putting the secret in the url be no longer considered "secret" or "sane"?

**Comment by tonyg** [comment]
It doesn't have to be in the clear in the URL. I've previously serialized, encrypted and authenticated continuations including secret state in order to place them in a URL parameter. Upon verification and decryption, I know it's a real continuation that really did originally come from me.

**Comment by julien51** [comment]
But if you're a sane subscriber you will change your callback URL pattern frequently, which means hat you would have to keep track of such pattern outside of them?
Again, I think the use case you're describing is pretty edgy and would require a change for all subscribers...

**Comment by tonyg** [comment]
Why would one change one's callback URL pattern frequently? Nevertheless, I think I've shown that a stateless subscriber is at least a possibility, except for the requirement to remember to renew one's lease.

**Comment by julien51** [comment]
You need to change your callback frequently for security reasons. The question is not so much to know that it's possible... but whether it's actually a practice and a good one. I don't think you hav demonstrated either of these things.

**Comment by tonyg** [comment]
... do you mean change the specific callback URL frequently for security reasons, or change the callback *pattern* (i.e. template, or schema) frequently for security reasons? The former I can understand, and it seems that it's mentioned in the spec even, but the latter doesn't make a lot of sense to me.

Assuming you mean that one should change the specific callback URL, then, this is not incompatible with stateless subscriptions. Upon unsubscription notification, complete with encoded state passed as part of the expiring callback URL being activated, the server would compute a new URL including updated state, and use that as the callback for the subscription renewal.

Statelessness allows scaling up a service in ways that a stateful service cannot be scaled; see the evaluations in section 6 of [this paper](https://jeapostrophe.github.io/home/static/icfp065-mccarthy.pdf) for a web-service setting and section 6 of [this paper](https://www.cs.cornell.edu/andru/papers/trickles.pdf) for a transport protocol setting. The intuition is that since the server doesn't need to store any per-client state, it can scale to an arbitrary number of clients.

**Comment by julien51** [comment]
Hi! Sorry for the delay!
Yes, I mean change the callback URL frequently with maximum entropy so that involves changing the callback pattern (there should be no visible pattern since we recommend capability URLs in the spec).

**Comment by aaronpk** [comment]
I'm still struggling to see a benefit of this unsubscription notification that isn't achieved by other means. 

If you're coding a subscriber defensively, then you shouldn't be relying on the hub's unsubscription notification to know when your subscription expired, you're going to need to store that state somewhere on the subscriber anyway.

**Comment by tonyg** [comment]
@aaronpk, as I wrote above, it'd be possible to have all necessary state in the callback URL itself, *except* for the fact that subscriptions expire silently. If there were an unsubscription notification, you could have a subscriber remember literally nothing about the subscription: its memory would be refreshed every time the hub invoked the callback, and the callback would be invoked every time anything changed regarding the subscription.

A second benefit of having a notification sent to a callback on expiry is that *reactive* or *passive* subscribers can be used. Imagine a subscriber that doesn't have a cron or a running thread, it simply passively responds to URLs. Maybe it's written in PHP on a simple webhost. How does such a subscriber renew its subscription without being given a notification? Seen this way, this proposed notification looks more like a lease keepalive.

If part of the point of PSHB is to make the hubs smart and allow the subscribers to be dumb, which ISTR was part of the rationale at some time in the past, then it'd be nice to allow stateless subscribers and passive subscribers.

**Comment by aaronpk** [comment]
But my point is that if you rely entirely on the hub behaving as expected, you are very likely going to completely miss some subscriptions due to broken hubs, and you'd never even know about it because the subscriber has no state at all. A subscriber that wants to ensure it's always subscribed is going to have to be proactive.

**Comment by tonyg** [comment]
There's not a lot one can do about broken hubs as a subscriber.

I think it's interesting that this proposed notification enables three quite distinct use cases: stateless subscribers, passive subscribers, and reacting to early subscription terminations.

I can see why stateless subscribers might not be very interesting yet, given that noone currently has the scale of deployment it enables. But I think the idea of a passive subscriber is pretty compelling, especially given the dumb-subscriber, let's-be-event-driven-and-not-polling-based design of PSHB. And *early* subscription termination (e.g. on permission-change, or administrative action) is impossible for the subscriber to respond to in a timely way without polling.

Being told that "after this point, you won't get any more notifications, for this reason" seems pretty useful to me.

**Comment by dissolve** [comment]
As a subscriber, if the hubs is broken, you can go back to polling.  Something you would need anyway as not everything will have a hub.  If the hub breaks you would never update at all.

The hub breaking case means you need to maintain a state, no matter what, so making someone maintain a state anyway doesn't seem like any burden at all.

**Comment by dissolve** [comment]
I've been going over and over this proposal and I see several issues with it.

First of all, no hub currently implements it, which means that unless we make this a MUST, clients cannot rely on it.  We previously agreed to avoid code changes to existing implementations wherever possible so that we can actually formalize and clarify what is being done today, not experiment.  So at best, I could only see this as an experimental extension and proposed requirement for future versions of the spec.  Though I do suggest that if this is something you really want, go and incubate it first and see if there are other issues we are not seeing.

Second, This seems like a really bad thing for clients.  This would limit the client to only working correctly on 100% conformant hubs that never have any errors.  Its usually best to code defensively and this is completely the opposite.  If a hub goes down and the publisher changes hubs, the subscription is lost forever, if the hub fails to send the unsubscribe notification, the subscription is lost forever, if the client fails to parse the unsubscribe correctly, the subscription is lost forever, etc.  The advantages of being stateless and having no sort of cron script also means that you can use ONLY websub, there is no falling back to just polling if the subscriber stops using their hub or if you just want to subscribe to feeds that don't use websub at all.  The disadvantages for users far outweighs the benefits in my opinion.

Next, This is actually really bad for the hubs.  First, this would make it very easy for a stateless client to accidentally subscribe to a feed multiple times.  Since they don't know if they are subscribed or not and the urls are most likely unique, one actual client could be subscribed with numerous URLs to one feed, just making bloated storage and traffic for the hub.  The hub would now be required to ensure delivery of unsubscribe notifications.  This means the hub has to figure out what to do if the unsubscribe notification is not getting delivered, say for temporary outage by the client.  Does the hub keep retrying? for how long?  The hub will have to maintain another state of a client needing to still be notified, and how many times it has tried, etc.   This basically tell hubs to just make your leases as long as possible so you don't ever have to deal with this issue, which we have dealt with before and said its really bad practice.

As I said, if you really want to work on this, it would make a fine extension to experiment with, but I would give up any expectation of implementing it totally statelessly unless you are only looking to have your client work with very specific hubs.

**Comment by sandhawke** [comment]
Tagging @tonyg -- it's been a while since there's been activity on this thread, and WebSub is at the point of needing to resolve all open issue.

@dissolve wrote a lot there.   I think the first point might be enough.   My understanding is we're postponing any change to the protocol that would require every hub to change, as not being feasible in the currently chartered Working Group.   If you don't know whether a hub's going to have this feature, then it really does no good.   (Assuming it does this when it doesn't, leaves things pretty broken.)  On the other hand, if there is a way to tell that a hub has this feature, then it can be an extension, and we don't need it mandated at this point.

**Comment by tonyg** [comment]
@dissolve, thank you for your comments. Your point that no hub implements unsubscription notifications is good. It's quite possible that the group's charter doesn't extend to this kind of proposal.

Setting that aside, your points about impact on clients indicate that "stateless" (S) or "passive" (P) operation isn't for everyone. Which is certainly true. But I can imagine situations where S/P operation would still be useful, *even in the face of the challenges you identify*. And of course S/P operation would be an option, not a requirement, so only those users opting in to S/P would be subject to the disadvantages you see.

Regarding hubs, unsubscription notifications in no way affect the ease or difficulty of accidentally subscribing to a feed multiple times. Your comments about this apply only to S/P operation (and I am not sure your assumptions are valid even in that case).

Your point about the requirement to ensure delivery of unsubscription notifications is definitely true. However, hubs are already required to ensure delivery of other kinds of notifications---content notifications!---including retry, backoff, eventual giving-up, etc. There's no reason the same techniques could not be used for this kind of notification, too.

---

I'd like to ask everyone to not concentrate unduly on S/P operation. It isn't the main or original thrust of the idea. It's just one thing that could be done, for users willing to accept the tradeoffs, if unsubscription notifications were introduced and used in case of lease expiration as well as in other circumstances.

The main thrust of the idea is that the hub can tell the subscriber when the subscription is cancelled, for any reason. That's it. That covers not only lease expiration, but also permission changes, topic resource disappearance (404/410), too many failed delivery attempts, administrative action, and so on and so forth. There are lots of reasons a subscription might be cancelled ahead of its expiry. It *still* seems useful to me to be told that "after this point, you won't get any more notifications, for this reason".

**Comment by tonyg** [comment]
I was thinking about this last night, and came up with a different perspective on the topic that might be interesting.

WebSub can be seen as doing *state replication*. It communicates an up-to-date picture of the state of some resource, the topic. As the topic changes, notifications are sent out, with the goal being that the subscriber's beliefs about the state of the topic should change to match the actual state of the topic.

So far so good. But there's *another* piece of state involved: the state of the *subscription*. It might be nice to let WebSub make a good effort to keep the subscriber's beliefs about the state of each *subscription* in sync with the actual state of that subscription.

**Comment by tonyg** [comment]
@sandhawke, it's certainly something that *could* appear as an extension. I'd like to still give the proposal serious consideration before deferring it, however, because once WebSub is finalized, I think the chances of making substantive changes to it drop immensely. We'll be stuck with whatever warts make it into the final spec (such as, for example, use of GET for verification).

**Comment by tonyg** [comment]
On the other hand, none of the existing users of PSHB seem to be (?) upset about there not being unsubscription notifications. (How would we know?) Is it a complete non-problem? Or would uptake of the protocol be even higher than it is, if only unsubscription notifications were a thing? Probably more likely the former :-)

On the gripping hand, time really is running out, I suppose. Properly spec'ing, implementing, and evaluating this idea would almost certainly take more time than is available.

**Comment by sandhawke** [comment]
@tonyg, thanks for replies.   I love the state-replication view (eg using PATCH to transmit diffs and PUT to transmit full versions), and the meta approach you suggest is pretty cool.    I'm not sure what we can do on that without requiring changes from all servers, though....   

Do you agree with @dissolve that your proposal would require every server to change, in order to be useful?   That is, are you proposing servers MUST try to notify clients when subscriptions expire?   Or only that they MAY?     And if MAY, is there a way for the client to know if the server's taken on this obligation?

**Comment by tonyg** [comment]
@sandhawke, yes: either every server must change, or some form of feature negotiation must take place. For example, something analogous to the existing lease expiry negotiation.

Concretely, perhaps request unsubscription notifications with `hub.options=notify-unsubscription` and expect to see the same in the subscription-verification request. If it's missing, the server clearly had no idea what you were asking for. Objection: some servers might choke on unexpected parameters. Counter-objection: try with the `hub.options` parameter, and if it fails, try again without. Much cleaner just to make it a MUST ;-)

**Comment by sandhawke** [comment]
@tonyg, rather than using an options parameter, we can keep things orthogonal and loosely-coupled by using a separate parameter for each option/extension.   So, in this case, something like hub.notify-when-subscription-ends=true.   Clients can send this without fear, because the spec says "Hubs MUST ignore additional request parameters they do not understand."  And, as you say, hubs that understand this can echo it back to confirm.

To me, this is a very simple and direct approach.   People can start doing this right now, without anyone's permission or negotiation.

Yes, we should probably make an extension registry, like the ActivityStream extension registry (or the link type registry).   A little table that says for 'notify-when-subscription-ends' here's the little description of what you're supposed to do.   That can be maintained by the https://www.w3.org/community/swicg/ .

In contrast, we can't really -- in practice -- mandate people change their websub implementations.  In general, the only way we could really make a breaking change would be to create a new link relation and use it instead of rel=hub.  (PubSubHubbub claimed the 'hub' link relation, of course).   We can keep using rel=hub as long as we're compatible with PubSubHubbub  Of course in practice there's a little wiggle room, like when things in practice are implemented in different ways, and when all the implementors agree, but to me it doesn't seem right to pursue a breaking change when a negotated feature would work just fine.

Now, you could argue the negotiated feature should be in the spec instead of in an extension.  That would increase awareness of it, and it would tend to be more widely implemented.  In the abstract, that would be fine with me, personally.  The problem is that we can't move forward to Recommendation unless we have multiple implementations of every feature in the next five weeks, so the question is would multiples hubs and multiple client libraries implement this immediately?

Personally, I'd rather put energy into making sure we stay on track with the stuff we've already got, which is going to be hard enough, given our timeline.  So I'm really hoping the extension route sounds okay to you.  You can write the first WebSub extension spec!   :-)

**Comment by tonyg** [comment]
@sandhawke, that's all very reasonable. I'll try my hand at writing an extension spec. (Though I feel compelled to remark that no-one *has* a websub implementation to change, yet! There are a few PSHB implementations, of course... :-) )

So, I think the conclusion of this discussion is: For this iteration of the spec process, we will not include unsubscription notifications, but if it is presented as an extension, we can consider it again then.

If that's a fair summary, I'm happy enough. I'll mark this closed; perhaps there's some label that can be applied to indicate "revisit in future" or something.
