### ISSUE TITLE
Target Attributes for link headers

### ISSUE THREAD

**Issue by leipert** [w3c/websub#80]
The WebSub spec does not specify whether it is okay to specify target attributes.

Would the following discovery link headers be okay? 

```
Link: <http://example.org>; rel="self"; title="example",
	﻿﻿﻿﻿<http://example.org/hub>; rel﻿="hub"; title="example hub"
```

**Comment by aaronpk** [comment]
The spec refers to RFC 5988 "Web Linking" which allows including other attributes. Were you finding any problems with using the title attribute in consumers? I'm not sure where in the spec it could be made explicit that it's either okay or not okay, since the spec doesn't even include any examples of Link headers, it just refers to RFC 5988.

**Comment by leipert** [comment]
Thanks for your answer. I do not have any problems with it anywhere. I just wanted to clarify.

Maybe it would be helpful to add examples for each type of discovery.

From my perspective this issue can be closed 👍
