### ISSUE TITLE
Topic/Hub/Callback cardinality

### ISSUE THREAD

**Issue by azaroth42** [w3c/websub#83]
The specification does not state the cardinality of the relationship between topics and hubs.  Given that you have to send the topic in the subscribe request, the implication is that it is not one to one, and many topics can share the same hub but that is not stated anywhere (that I can find). 

The specification recommends, though still somewhat implicitly, that there be one callback URL per Topic.

This distinction seems inconsistent. If the subscriber (typically less capable than a hub) SHOULD implement multiple callback endpoints, then it seems like the hub SHOULD also do the same?  Otherwise, drop the recommendation for the callbacks?

**Comment by aaronpk** [comment]
Subscribers can implement unique callback URLs just by using query string parameters, which is relatively easy to support.

The desire to have a single hub URL is for the ease of publishers, not hubs. Requiring unique hub URLs per topic URL means the burden is on the publisher to figure out what hub URL to use for every URL it wants to publish.

**Comment by azaroth42** [comment]
And hubs could be implemented with query string parameters too, no?  `?huburl=topicurl` would be trivial other than the (necessary anyway) URL encoding. What's good for the goose... :)

**Comment by aaronpk** [comment]
Your original point was that there is no explicit mention of the fact that hubs typically use a single URL for multiple topics. This is not a strict requirement of the spec, since it's entirely possible for a publisher and hub to have their own agreement, such as when the publisher and hub are part of the same software (e.g. a built-in hub as a Wordpress plugin.)

In general, the hub-publisher arrangement is left out of this spec, since this spec is designed for subscribers to get notifications when a resource is updated. A couple years ago, I wrote up [a complementary guide](https://indieweb.org/how-to-push) for standardizing the relationship between publishers and hubs when they are not part of the same system.
