### ISSUE TITLE
Subscription migration is unclear

### ISSUE THREAD

**Issue by kevinmarks** [w3c/websub#98]
Concrete example from the fediverse: https://github.com/tootsuite/mastodon/issues/177#issuecomment-292780728

A person wants to move their primary location from, say, mastodon.social to xoxo.zone  - how could mastodon.social tell the subscribers that are renewing their topic feed to go to the xoxo.zone topic instead (assuming we have already done the handshake between the two domains to confirm the account migration)? 
A change of rel-self? 
A 301 to the new domain's hub (this was not recommend in https://github.com/w3c/websub/issues/73 )

**Comment by aaronpk** [comment]
This problem is documented here, with a potential solution: https://github.com/pubsubhubbub/PubSubHubbub/wiki/Moving-Feeds-or-changing-Hubs

The specific suggestion is that the old hub should be aware of the new topic URL, and when it delivers the payload, it includes the new topic URL as the rel=self header. Since subscribers should be using unique per-subscription URLs, the subscriber recognizes that this rel=self does not match the previous rel=self for the subscription, so this must be a topic URL change. The subscriber can then do discovery on the new topic URL and find the new hub, and the migration is complete. This does require cooperation on the part of the previous topic URL's hub.

The other way to make this happen without the hub's cooperation is that the old topic URL can return a 301 redirect to the new topic URL. When a subscription expires, the subscriber will fetch the topic URL again, which will redirect to the new topic URL which will contain the new hub and new rel=self value. This is a little simpler since the previous hub doesn't need to do anything, but potentially will drop the notifications from the time between creating the redirect and the subscription expiration.

**Comment by aaronpk** [comment]
Upon further thought, the safest thing to do is the second approach I described. 

* The old topic URL should send a redirect to the new topic URL. This will provide a seamless transition for any clients polling the topic URL.
* When the subscription expires, clients will fetch the topic URL, will be redirected to the new topic URL.
* The client will see the new topic URL as the `rel=self` URL and subscribe to the new topic URL at the new hub. 

There shouldn't even be any new code needed to make this work.

This paired with the extension that will send a notification when a subscriber is unsubscribed (#16) would mean that subscribers wouldn't even miss any notifications.

**Comment by tonyg** [comment]
> ... subscribers wouldn't even miss any notifications.

I think I'd write this "wouldn't miss *many* notifications"! But, from the point of view of WebSub as a state-replication protocol, notifications are strictly an optimization; retrieving the latest version of the topic resource itself papers over any gaps in the notification stream.

**Comment by aaronpk** [comment]
I've added two tests for this: [201](https://websub.rocks/subscriber/201) and [202](https://websub.rocks/subscriber/202). Is it worth adding an informative section to the spec describing how to redirect subscribers?

**Comment by aaronpk** [comment]
As discussed on today's call, I'll add an informative section describing subscription migration using this method.

**Comment by aaronpk** [comment]
@kevinmarks Please review the new text and let me know if you think that's clear enough for people:

https://w3c.github.io/websub/#subscription-migration

**Comment by kevinmarks** [comment]
I think that is clear, though you could specify a 301 redirect explicitly.
